### PR TITLE
added notification-bookings public API endpoint

### PR DESCRIPTION
**Pull request by SiimKirjanen**

### CODE REVIEW

**Comment by omtr** [comment]
i try to get this running but i have the feeling that the event is not triggered at all.
this line should be sufficient to trigger myFunction(), right?

`add_action('seatreg_action_booking_approved', 'myFunction');`

**Comment by omtr** [comment]
thanks Siim,
just to clarify so i dont get you wrong:

- this action should be placed in the functions.php of the (child) theme
- it will trigger custom code when a booking is approved, regardless if it was approved by a direct payment (e.g. with Stripe or PayPal) or by a manual approval in the SeatReg backend
- implemented since version 1.38.0

still no idea where my problem is, i tried to write something in the debug log so i can see if its triggered or not, but so far no success...

**Comment by SiimKirjanen** [comment]
- Never tested those hooks with WordPress themes. Tested with other plugins. Maybe the problem is here. Need to test.
- Currently it will not trigger when using Stripe or Paypal payments. But that is something I can add.
-  The custom hooks were added with version 1.36.0

**Comment by SiimKirjanen** [comment]
Just tested with twentytwentyone WordPress theme. The 'seatreg_action_booking_approved' hook is triggering fine

**Comment by omtr** [comment]
thanks Siim! Webhooks for PayPal / Stripe payment approval would be great! I will switch the theme to Twentytwentyone on our staging site, right now its Astra with Elementor.

**Comment by SiimKirjanen** [comment]
Let me know if it helped.

**Comment by omtr** [comment]
will do!

**Pull request merged**
